spring.application.name=smart-library

# DATABASE CONNECTION
spring.datasource.url=jdbc:mysql://localhost:3306/smart_library
spring.datasource.username=root
spring.datasource.password=45678910
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT CONFIG
app.jwt.secret=YourSuperSecretKeyThatIsAtLeast256BitsLong12345678
app.jwt.expiration=86400000

# SERVER
server.port=8080
